version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: my-app-db
       MYSQL_ROOT_USER: root
       MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./betogether:/code
    ports:
      - "8000:8000"
    depends_on:
      - db