# Generated by Django 3.2.12 on 2022-03-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profiledetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileDetails',
            new_name='ProfileDetail',
        ),
    ]
